<<<<<<< HEAD
application: pnadityapn
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/
  static_dir: static

- url: /aboutme
  static_dir: aboutme

- url: /.*
  script: blog.application
=======
application: pnadityapn
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/
  static_dir: static

- url: /aboutme
  static_dir: aboutme

- url: /.*
  script: blog.application
>>>>>>> b63274a9769bf4f24b15a8803c067fc5bff29c79
